### ISSUE TITLE
Tests failing with latest tpm2.0-tools version

### ISSUE THREAD

**Issue by DomiNic5787** [tpm2-software/tpm2-tss-engine#106]
Tests need to be adapted to new parameters in tpm2.0-tools!

**Comment by AndreasFuchsSIT** [comment]
Hmmmm.. either that or we checkout a certain commit-id until the tpm2-tools' 4.x release.
I guess I'd opt for the latter...

**Comment by diabonas** [comment]
It might help a bit to use long options (``--object-attributes``) instead of short options (``-b``), since these have proven to be more stable in the past. There also have been some changes of course, but at least with these there is no confusion regarding [capitalisation (`-b` vs. `-B`)](https://github.com/tpm2-software/tpm2-tools/pull/1330#issuecomment-469744759) ;)

**Comment by diabonas** [comment]
Or we could use the stable tpm2-tools 3.X branch in combination with tpm2-abrmd: using the 3.X branch was proposed in #61, but the problem was that it is missing `tpm2_flushcontext`, which leads to test failures when the TPM doesn't have space for new transient objects any more. With tpm2-abrmd this wouldn't be a problem because clearing the TPM is done by the resource manager.
