### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by raghuncstate** [tpm2-software/tpm2-tss-engine#60]
Possible leak in tpm2-tss-engine-rsa.c in populate_rsa(). BN's are being allocated but not being free. It is possible that some of them were allocated and some of them were not in which case we must free the ones that were allocated.
Similar issue in tpm2tss_rsa_makekey(). EVP_PKEY is free'd but not the RSA key.

**Comment by AndreasFuchsSIT** [comment]
Actually, I had a segfault issue in one of the other issues, if I freed the RSA key after the assign to EVPpkey. I figured that EVPpkey takes ownership of the RSA key during assign.
Can you confirm or deny this assumption ? Or did you see this on valgrind or via code review ?

Thanks a lot for the input in any case...

**Comment by raghuncstate** [comment]
Hello, I saw the issue via code review. Noticed it while looking over the code.
For the EVP_PKEY case, you're right, EVP_PKEY takes ownership of the RSA key after the assign and should be free'd and there is no issue with tpm2_tss_rsa_makekey().
The populate_rsa() function still seems like an issue though. Is there a reason this might not be a problem ? i dont see a reason why the BN's should not be free'd on error.

**Comment by AndreasFuchsSIT** [comment]
For https://github.com/tpm2-software/tpm2-tss-engine/blob/157c305ff743d2e2a7d343979b398712da56f17d/src/tpm2-tss-engine-rsa.c#L310 and following, I think the RSA object will free when it's destroyed, correct ?

For https://github.com/tpm2-software/tpm2-tss-engine/blob/157c305ff743d2e2a7d343979b398712da56f17d/src/tpm2-tss-engine-rsa.c#L379 I guess we could free the allocated parts. I guess I ignored this since we will subsequently fatally crash anyways. But I guess there's room for improvement here.

**Comment by raghuncstate** [comment]
for tpm2-tss-engine-rsa.c: 310- correct. RSA_free() will destroy all the BN's.
For tpm2-tss-engine-rsa.c: 379: Correct. That was the intent. Not functionally broken, will just be for memory cleanliness.

**Comment by AndreasFuchsSIT** [comment]
ok, noted...
Patches welcome...

**Comment by raghuncstate** [comment]
#64

**Comment by AndreasFuchsSIT** [comment]
Solved in #64
